FROM golang:latest as builder
WORKDIR src
COPY . .
RUN go install go.k6.io/xk6/cmd/xk6@latest
RUN xk6 build latest --with $(go list -m)=.

# Use the operator's base image and override the k6 binary
FROM loadimpact/k6:latest
COPY --from=builder /go/src/k6 /usr/bin/k6